import { COLORS_PALETTE } from "./consts";

export default {
  1: {
    rows: 4,
    cols: 4,
    colors: COLORS_PALETTE[0],
    enemyColorsCount: 1,
    countdownSeconds: 60,
    allowRepeatedColors: false,
  },
  2: {
    rows: 4,
    cols: 4,
    colors: COLORS_PALETTE[0],
    enemyColorsCount: 1,
    countdownSeconds: 50,
    allowRepeatedColors: false,
  },
  3: {
    rows: 4,
    cols: 4,
    colors: COLORS_PALETTE[0],
    enemyColorsCount: 1,
    countdownSeconds: 40,
    allowRepeatedColors: false,
  },
  4: {
    rows: 4,
    cols: 4,
    colors: COLORS_PALETTE[0],
    enemyColorsCount: 2,
    countdownSeconds: 35,
    allowRepeatedColors: false,
  },
  5: {
    rows: 4,
    cols: 4,
    colors: COLORS_PALETTE[0],
    enemyColorsCount: 2,
    countdownSeconds: 30,
    allowRepeatedColors: false,
  },
  6: {
    rows: 5,
    cols: 5,
    colors: COLORS_PALETTE[1],
    enemyColorsCount: 2,
    countdownSeconds: 50,
    allowRepeatedColors: false,
  },
  7: {
    rows: 5,
    cols: 5,
    colors: COLORS_PALETTE[1],
    enemyColorsCount: 2,
    countdownSeconds: 45,
    allowRepeatedColors: false,
  },
  8: {
    rows: 5,
    cols: 5,
    colors: COLORS_PALETTE[1],
    enemyColorsCount: 2,
    countdownSeconds: 40,
    allowRepeatedColors: false,
  },
  9: {
    rows: 5,
    cols: 5,
    colors: COLORS_PALETTE[1],
    enemyColorsCount: 3,
    countdownSeconds: 40,
    allowRepeatedColors: false,
  },
  10: {
    rows: 5,
    cols: 5,
    colors: COLORS_PALETTE[1],
    enemyColorsCount: 3,
    countdownSeconds: 35,
    allowRepeatedColors: false,
  },
  11: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[2],
    enemyColorsCount: 3,
    countdownSeconds: 60,
    allowRepeatedColors: true,
  },
  12: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[2],
    enemyColorsCount: 3,
    countdownSeconds: 50,
    allowRepeatedColors: true,
  },
  13: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[2],
    enemyColorsCount: 3,
    countdownSeconds: 45,
    allowRepeatedColors: true,
  },
  14: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[2],
    enemyColorsCount: 4,
    countdownSeconds: 50,
    allowRepeatedColors: true,
  },
  15: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[2],
    enemyColorsCount: 4,
    countdownSeconds: 45,
    allowRepeatedColors: true,
  },
  16: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[3],
    enemyColorsCount: 3,
    countdownSeconds: 60,
    allowRepeatedColors: true,
  },
  17: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[3],
    enemyColorsCount: 3,
    countdownSeconds: 50,
    allowRepeatedColors: true,
  },
  18: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[3],
    enemyColorsCount: 3,
    countdownSeconds: 45,
    allowRepeatedColors: true,
  },
  19: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[3],
    enemyColorsCount: 4,
    countdownSeconds: 40,
    allowRepeatedColors: true,
  },
  20: {
    rows: 6,
    cols: 6,
    colors: COLORS_PALETTE[4],
    enemyColorsCount: 3,
    countdownSeconds: 45,
    allowRepeatedColors: true,
  },
};
